[platformio]
default_envs = supermini

[env:supermini]
platform = nordicnrf52@10.12.0
board = supermini_swd
framework = arduino
platform_packages =
    platformio/framework-arduinoadafruitnrf52@1.10700.0
build_unflags = -Os
build_flags = -O3
extra_scripts = post:scripts/package_dfu.py
upload_protocol = nrfutil
